### PR TITLE
Add event tracking for form validation

### PR DESCRIPTION
**Pull request by teneightfive**
- Add analytics object to send event tracking
- Track form errors by field and message

### CODE REVIEW

**Comment by marcofucci** [comment]
:+1: can I merge?

**Comment by teneightfive** [comment]
Can you think of anything else worth tracking?

Am tracking each field and validation message with this but not sure what else we want in terms of event tracking.

**Comment by teneightfive** [comment]
Most other stuff we can pull from simple page view tracking.

**Comment by marcofucci** [comment]
As we don't have db, if would be useful to track:

- number of types of enquiry
- in case of export, first part of the postcode

**Comment by teneightfive** [comment]
Yep, agreed. Have cleaned this one up so it's good to merge.

**Comment by marcofucci** [comment]
:+1:

**Pull request merged**
